name: 'coco_dbt'
version: '1.0.0'

profile: 'coco_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  coco_dbt:
    +database: CORTEX_ANALYST_DEMO
    +schema: DBT_SATYAM
    staging:
      +materialized: view
    int:
      +materialized: ephemeral
    marts:
      +materialized: incremental
    publish:
      +materialized: table
