coco_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: MCB71975
      user: SATYAMC
      role: CORTEX_USER_ROLE
      database: CORTEX_CODE_USECASE
      warehouse: CORTEX_ANALYST_WH
      schema: DBT_SCHAURAS
      threads: 4
