coco_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: MCB71975
      user: SATYAMC
      role: CORTEX_USER_ROLE
      database: CORTEX_ANALYST_DEMO
      warehouse: CORTEX_ANALYST_WH
      schema: DBT_SATYAM
      threads: 4
